### ISSUE TITLE
Extracting root filesystem failed

### ISSUE THREAD

**Issue by DrizzlingSun** [pr0v3rbs/FirmAE#55]
root@attifyos:/home/iot/tools/firmAE/FirmAE# ./run.sh -c dlink /home/iot/tools/firmware-analysis-toolkit/DIR816.img 
[*] /home/iot/tools/firmware-analysis-toolkit/DIR816.img emulation start!!!

General Error: Cannot open file --run-as=root (CWD: /tmp/tmpuhbydzva) : [Errno 2] No such file or directory: '--run-as=root'

General Error: Cannot open file --preserve-symlinks (CWD: /tmp/tmpuhbydzva) : [Errno 2] No such file or directory: '--preserve-symlinks'

Traceback (most recent call last):
  File "./sources/extractor/extractor.py", line 446, in extract
  File "/usr/local/lib/python3.6/dist-packages/binwalk/__init__.py", line 10, in scan
    objs = m.execute()
  File "/usr/local/lib/python3.6/dist-packages/binwalk/core/module.py", line 784, in execute
    obj = self.run(module)
  File "/usr/local/lib/python3.6/dist-packages/binwalk/core/module.py", line 803, in run
    obj = self.load(module, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/binwalk/core/module.py", line 834, in load
    argv.update(self.dependencies(module, argv['enabled']))
  File "/usr/local/lib/python3.6/dist-packages/binwalk/core/module.py", line 866, in dependencies
    raise ModuleException("Failed to load " + dependency.name + " module")
binwalk.core.exceptions.ModuleException: Failed to load General module

General Error: Cannot open file --run-as=root (CWD: /tmp/tmpmm1kal4s) : [Errno 2] No such file or directory: '--run-as=root'

General Error: Cannot open file --preserve-symlinks (CWD: /tmp/tmpmm1kal4s) : [Errno 2] No such file or directory: '--preserve-symlinks'

Traceback (most recent call last):
  File "./sources/extractor/extractor.py", line 446, in extract
  File "/usr/local/lib/python3.6/dist-packages/binwalk/__init__.py", line 10, in scan
    objs = m.execute()
  File "/usr/local/lib/python3.6/dist-packages/binwalk/core/module.py", line 784, in execute
    obj = self.run(module)
  File "/usr/local/lib/python3.6/dist-packages/binwalk/core/module.py", line 803, in run
    obj = self.load(module, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/binwalk/core/module.py", line 834, in load
    argv.update(self.dependencies(module, argv['enabled']))
  File "/usr/local/lib/python3.6/dist-packages/binwalk/core/module.py", line 866, in dependencies
    raise ModuleException("Failed to load " + dependency.name + " module")
binwalk.core.exceptions.ModuleException: Failed to load General module
[-] Extracting root filesystem failed!
root@attifyos:/home/iot/tools/firmAE/FirmAE#

**Comment by pr0v3rbs** [comment]
Currently, FirmAE uses binwalk 2.3.3.

Please check your binwalk version.

**Comment by fdgnneig** [comment]
I had the same problem, and I'm sure my binwalk is version 2.3.3
Binwalk v2.3.3+28f7eb4

**Comment by fdgnneig** [comment]
Installed in ununtu20.04 can be used normally

**Comment by pr0v3rbs** [comment]
The current version of the binwalk can be checked in the `python3` with this command `import binwalk; binwalk.__version__`. (In the `root`)

If the version is not correct, please re-install the binwalk using this command (https://github.com/pr0v3rbs/FirmAE/blob/master/install.sh#L25-L31)

The binwalk need to be installed in the `root`.

**Comment by nhtri2003gmail** [comment]
Hey @pr0v3rbs, the binwalk repo has file deps.sh, which is corrupted due to a change of repo ubi_reader, hence that file cannot work properly.
But just installing using command `sudo python3 setup.py install` as instructed of binwalk will install binwalk. Then we just need to install sasquatch to make FirmAE work.

I modified the install.sh file of FirmAE a bit so it can install binwalk and work properly

Result of diff:

```diff
--- install.sh  2023-05-29 11:48:56.740200200 +0700
+++ install_modified.sh 2023-05-29 11:27:07.975255100 +0700
@@ -26,9 +26,16 @@
 wget https://github.com/ReFirmLabs/binwalk/archive/refs/tags/v2.3.3.tar.gz && \
   tar -xf v2.3.3.tar.gz && \
   cd binwalk-2.3.3 && \
-  sed -i 's/^install_unstuff//g' deps.sh && \
-  echo y | ./deps.sh && \
-  sudo python3 setup.py install
+  sudo python3 setup.py install && \
+  sudo apt-get install build-essential liblzma-dev liblzo2-dev zlib1g-dev && \
+  git clone https://github.com/devttys0/sasquatch && \
+  cd sasquatch/patches && \
+  wget https://github.com/devttys0/sasquatch/files/7776843/M1-Kali.patch.txt && \
+  patch patch0.txt M1-Kali.patch.txt && \
+  cd .. && \
+  ./build.sh && \
+  cd .. && \
+  rm -rf sasquatch
 sudo apt-get install -y mtd-utils gzip bzip2 tar arj lhasa p7zip p7zip-full cabextract fusecram cramfsswap squashfs-tools sleuthkit default-jdk cpio lzop lzma srecord zlib1g-dev liblzma-dev liblzo2-dev unzip

 cd - # back to root of project
```

[install.sh.zip](https://github.com/pr0v3rbs/FirmAE/files/11588527/install.sh.zip)
